name: autofix.ci
concurrency: 
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
on:
  pull_request:
    branches:
      # - dev
      # - master
      - staged
      - experimental
    paths-ignore:
      # - ".github/**"
      - "locale/**"
jobs:
  clang-format:
    name: clang format the code
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:

          fetch-depth: 2
      # format the latest commit
      - name: ubuntu install clang-format
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install clang-format
          (/home/linuxbrew/.linuxbrew/opt/clang-format/bin/git-clang-format --binary=/home/linuxbrew/.linuxbrew/opt/clang-format/bin/clang-format --style=file HEAD^) || true
      - uses: autofix-ci/action@v1


  css-js-html-format:
    name: format css/js/html/md
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - name: format css/js/html/md
        run: npx prettier@3.8.3 . --write
      - uses: autofix-ci/action@v1

  markdownlint:
    name: lint and fix markdown files
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - name: install markdownlint-cli
        run: npm install -g markdownlint-cli
      - name: fix markdown files
        run: markdownlint "**/*.md" --config .markdownlint.json --fix
      - uses: autofix-ci/action@v1

  update-crowdin:
    name: update crowdin.ts file
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - name: Install Qt
        uses: jurplel/install-qt-action@v4.3.1
        with:
          version: '6.7.2'
          target: 'desktop'
          tools: 'tools_qtcreator,qt.tools.qtcreator'
      - name: update crowdin.ts
        run: |
          lupdate -no-obsolete -no-ui-lines -locations none src -ts locale/crowdin.ts
      - uses: autofix-ci/action@v1