name: deploy_website 

on:
  push:
    branches:
      - staged 
    paths:
      - 'website/**'
  workflow_dispatch:

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install --only-binary :all: mkdocs-material==9.7.6
      - run: |
          cd website
          mkdocs gh-deploy --force
