name: deploy_website 
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - staged 
    paths:
      - 'website/**'
  workflow_dispatch:

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - run: pip install mkdocs-material==9.7.6
      - run: |
          cd website
          mkdocs gh-deploy --force
